[tool.poetry]
name = "django-hw"
version = "0.1.0"
description = ""
authors = ["Valeriya <chulkovav66@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
